ActionNotFound = "action '{{.Action}}' not found"
ChannelsAlreadyJoined = "❌The following channels were already joined: {{.Channels}}"
ChannelsNotFound = "❌Channel(s) not found"
CmdAddDescription = "Adds given 7TV emote to the channel"
CmdAddFailedToFetch7TV = "❌Failed to fetch user's 7tv data"
CmdAnnounceAdmin = "Only admins allowed..."
CmdAnnounceDescription = "(admin only) Make or preview pending announcements."
CmdAnnounceNoChannels = "No channels left to announce in"
CmdAnnouncePreview = "Would announce to {{.Channels}} channels. Full list send to logs."
CmdButtDescription = "Responds with butt to messages starting with butt"
CmdButtsbotDescription = "Replaces random syllables with butt"
CmdButtwordDescription = "Set word used by buttsbot in the author's channel or the specified channel to replace syllables"
CmdButtwordDisallowed = "❌You must be an admin or the channel's owner to change this setting"
CmdButtwordFailed = "❌Failed to set buttword"
CmdButtwordSuccess = "Successfully set {{.User}}'s channel buttword to {{.Word}}"
CmdDisableDescription = "Disables a command for all users in the channel"
CmdEditorAdded = "✅Added editor '{{.Editor}}'"
CmdEditorDescription = "Add or remove 7TV emote editors"
CmdEditorErrNotBroadcaster = "❌Only the broadcaster can set editors"
CmdEditorRemoved = "✅Removed editor '{{.Editor}}'"
CmdEnableDescription = "Enables a command for all users in the channel"
CmdGameDescription = "Duel with fatasswizardcat emotes"
CmdHelpDescription = "Get the full list of commands, or help with a specific command"
CmdJoinDescription = "Join the message author's channel or the specified channel"
CmdLanguageDescription = "Set the bot's language for the author or a specified channel"
CmdLocationDescription = "Set or get user's location. Used in commands related to weather and time."
CmdLocationDisallowedSetLang = "Not allowed to set language for '{{.User}}'."
CmdLocationFailedToSet = "Failed to set {{.User}}'s location  to '{{.Location}}'."
CmdLocationGet = "User {{.User}}'s location is '{{.Location}}'"
CmdLocationNotFound = "Location '{{.Location}}' not found."
CmdLocationNotSet = "Location not set for user '{{.User}}'."
CmdLocationSuccess = "✅Location for '{{.User}}' set to '{{.Location}}'."
CmdLocationTargetNotFound = "User '{{.User}}' not found."
CmdOptedIn = "✅ Opted in"
CmdOptionDescription = "Opt in to one or all commands"
CmdOptoutDescription = "Opt out of one or all commands"
CmdPartDescription = "Leave the message author's channel or the specified channel"
CmdPartNotJoined = "❌The following channels were not joined: {{.Channels}}"
CmdPartResult = "✅Successfully parted {{.Channels}}"
CmdPingDescription = "Responds with pong and latency to twitch in milliseconds"
CmdPingLatency = "Latency: %dms"
CmdPingMemory = "Memory: %d MiB"
CmdPingUptime = "Uptime: %s"
CmdRemoveDescription = "Removes given 7TV emote from the channel"
CmdSetLevelDescription = "Set a user's permission level"
CmdTimeFailedToLoadLocation = "Failed to load {{.User}}'s timezone '{{.Timezone}}'"
CmdTimeNotSet = "Location not set for {{.User}}."
CmdTimeResult = "User {{.User}}'s time is '{{.Time}}'"
CmdTimeTargetNotFound = "User {{.User}} not found."
CmdWeatherApparentTemp = " {{.CurrentTemp}}{{.CurrentTempUnits}}, feels like {{.Temp}}{{.Unit}}. "
CmdWeatherCloudCover = "Cloud cover: {{.Cover}}{{.Unit}}. "
CmdWeatherDescription = "Get current weather for an user based on their defined location."
CmdWeatherFailedToLoadLocation = "Failed to load weather for '{{.Name}}'"
CmdWeatherNoRain = "No rain. "
CmdWeatherRain = "Rain: {{.Rain}}{{.Unit}}. "
CmdWeatherSnowfall = "Snowfall: {{.Snowfall}}{{.Unit}}. "
CmdWeatherWindspeed = "Wind speed: {{.Speed}}{{.Unit}}. "
CmdYoinkDescription = "Add given 7TV emote from a channel to another"
CmdtimeDescription = "Get user's time based on their defined location."
CommandCannotBeDisabled = "❌Command '{{.Command}}' cannot be disabled"
DisabledCommands = "✅Disabled command '{{.Command}}'"
DuelExists = "One of the players already has an active duel"
DuelNoTarget = "Please set a duel target"
DuelNotExists = "Found no active duel for player"
DuelStart = "duel started! Your turn {{.Player}}. Options are: fireball, water, potion, barrier"
DuelWon = "{{.Winner}} won! 👏"
EmoteAlreadyInChannel = "❌Emote '{{.Emote}}' already in '{{.ToChannel}}'."
EnabledCommands = "✅Enabled command '{{.Command}}'"
FailedFetchSevenTVChannel = "Failed to fetch sevenTV channel for '{{.Channel}}'"
FailedFetchSevenTVChannel2 = "Failed to fetch sevenTV channel for '{{.Channel}}'"
FailedFindActiveEmoteSet = "❌Failed to find active emote set for {{.Channel}}"
FailedToFetchChannel = "❌Failed to fetch channel '{{.Channel}}'"
Help = "Commands: http://hashbot.dev ● For help with a specific command: help <command>"
IncrementPotionErr = "{{.Source}}, you can't use more than 1 potion!"
MustBeAdmin = "❌You must be an admin to use this command"
MustBeModerator = "❌You must be a moderator to use this command"
NotAnEditor = "❌User '{{.User}}' has not set the bot as an editor."
NotEditor = "❌You must be an editor to use this command"
OptedOut = "✅ Opted out"
SetBarrierEffect = "{{.Source}} applied a barrier => {{.Action}} {{.Barrier}}🛡️"
SetDamageEffect = "{{.Source}} attacked {{.Target}} => {{.Action}} {{.Health}}❤️ - {{.Damage}}❤️ + {{.Barrier}}🛡️ = {{.HpLeft}}❤️"
SetHPEffect = "{{.Source}} healed => {{.Action}} {{.HP}}🧪"
SetUserLanguageFail = "❌Failed to set user's language"
SetUserLanguageResult = "✅Set {{.Username}}'s language to {{.Language}}"
UnknownCommand = "❌Unknown command '{{.Command}}'."
UpdatedPermissions = "✅ Updated {{.User}}'s permission to {{.Permission}}!"
Usage = "❌Usage: {{.Usage}}"
UserNotFound = "User '{{.User}}' not found"
WrongTurn = "the next play is {{.Target}}'s, not yours!"
YoinkFromChannelToChannel = "❌Can't yoink from '{{.From}}' to '{{.To}}', they are equal."

[AddedEmotes]
one = "✅Added emote '{{.Emotes}}' from '{{.FromChannel}}' to '{{.ToChannel}}'"
other = "✅Added emotes '{{.Emotes}}' from '{{.FromChannel}}' to '{{.ToChannel}}'"

[CmdAddAddedEmote]
one = "Added {{.Count}} emote: {{.Emotes}}"
other = "Added {{.Count}} emotes: {{.Emotes}}"

[CmdAddFailedToAddEmote]
one = "Failed to add {{.Count}} emote: {{.Emotes}}"
other = "Failed to add {{.Count}} emotes: {{.Emotes}}"

[CmdJoinResult]
one = "✅Joined channel {{.Channels}}"
other = "✅Joined channels {{.Channels}}"

[EmotesAlreadyInChannel]
one = "❌Emote '{{.Emotes}}' already in '{{.ToChannel}}'."
other = "❌Emotes '{{.Emotes}}' already in '{{.ToChannel}}'."

[FailedFindEmote]
one = "❌Failed to find emote '{{.Emotes}}' in '{{.Channel}}'."
other = "❌Failed to find emotes '{{.Emotes}}' in '{{.Channel}}'."
