[ActionNotFound]
hash = "sha1-0be5dd585acbf3c3778b69f7d5e9af675d3baf43"
other = "Ação '{{.Action}}' não encontrada"

[AddedEmotes]
hash = "sha1-cda64e644b347b9afd6f8592ca881f7b51cf05fc"
many = "✅Adicionados emotes '{{.Emotes}}' de '{{.FromChannel}}' para '{{.ToChannel}}'"
one = "✅Adicionado emote '{{.Emotes}}' de '{{.FromChannel}}' para '{{.ToChannel}}'"
other = "✅Adicionados emotes '{{.Emotes}}' de '{{.FromChannel}}' para '{{.ToChannel}}'"

[ChannelsAlreadyJoined]
hash = "sha1-c6893a737287b297c51eb74260eb575f3dd0df3c"
other = "❌Os seguintes canais já foram ingressados: {{.Channels}}"

[ChannelsNotFound]
hash = "sha1-cb09c76f93d23e40662f4682584f8682a7bec2b4"
other = "❌Canais não encontrados"

[CmdAddAddedEmote]
hash = "sha1-ef991d6469f280f62cd37b6e1810aab85d10f6c3"
many = "Adicionados {{.Count}} emotes: {{.Emotes}}"
one = "Adicionado {{.Count}} emote: {{.Emotes}}"
other = "Added {{.Count}} emotes: {{.Emotes}}"

[CmdAddDescription]
hash = "sha1-eef42810e3d6f31b7e69b150ebc2c850efd31216"
other = "Adiciona o emote do 7TV especificado ao canal"

[CmdAddFailedToAddEmote]
hash = "sha1-929aecb65abc7e798e92ee786b9fa9323888577e"
many = "Falha ao adicionar {{.Count}} emotes: {{.Emotes}}"
one = "Falha ao adicionar {{.Count}} emote: {{.Emotes}}"
other = "Falha ao adicionar {{.Count}} emotes: {{.Emotes}}"

[CmdAddFailedToFetch7TV]
hash = "sha1-03ca44c4fb76551adc2fbd2452d73e51384af973"
other = "❌Falha ao obter dados do 7TV do usuario"

[CmdAnnounceAdmin]
hash = "sha1-b2e9946dafab95d0d1c702f67a17062241d2761f"
other = "Somente administradores permitidos..."

[CmdAnnounceDescription]
hash = "sha1-adcc125a8ee1fd9e181538d0fcdfc7d639669368"
other = "(somente administrador) Criar ou visualizar anúncios pendentes."

[CmdAnnounceNoChannels]
hash = "sha1-865eaf0f6ff1a0a3bdcffc66cb1b63cd55c3184a"
other = "Não há mais canais para anunciar"

[CmdAnnouncePreview]
hash = "sha1-676839df457a123aef77050dea05b46fc4df418b"
other = "Anunciaria para {{.Channels}} canais. Lista completa enviada para logs."

[CmdButtDescription]
hash = "sha1-043781a2eb25e91f22f1b48b68a27d6536a735e8"
other = "Responde com butt para mensagens iniciadas com butt"

[CmdButtsbotDescription]
hash = "sha1-ca755e3450c6f5c818803819e55cf95c9b916cbd"
other = "Substitui silabas aleatorias com butt"

[CmdButtwordDescription]
hash = "sha1-f39ea764dd752a58976fd7412eded6e252b6e0d3"
other = "Altera a palavra usada pelo buttsbot para substituir silabas no canal do autor da mensagem ou no canal especificado"

[CmdButtwordDisallowed]
hash = "sha1-5b5906af634ab7ba1fe3c4302c4858b19ca14a64"
other = "❌Você deve ser o dono do canal ou um admin para alterar essa configuração"

[CmdButtwordFailed]
hash = "sha1-a1d4317522b1613248ef88236e9edcdb21d9c155"
other = "❌Falha ao alterar a buttword"

[CmdButtwordSuccess]
hash = "sha1-7eb567e219a3d9890bae3880f5e2d6b6ef626c9a"
other = "Buttword do canal {{.User}} alterada com sucesso para {{.Word}}"

[CmdDisableDescription]
hash = "sha1-8b4a5416139723a65611ab6713b89eeb177de509"
other = "Desabilita um comando para todos os usuarios no canal"

[CmdEditorAdded]
hash = "sha1-ee670201736cce96498722a7261837247ce7cbf9"
other = "✅Editor adicionado '{{.Editor}}'"

[CmdEditorDescription]
hash = "sha1-58f61ccd02c20f03e009d2f84fc149d96aa9ae30"
other = "Adiciona ou remove editores do 7TV"

[CmdEditorErrNotBroadcaster]
hash = "sha1-4df8b673a36cff38ade8753fae2393fb4bd623ae"
other = "❌Apenas o dono do canal pode alterar editores"

[CmdEditorRemoved]
hash = "sha1-3117ec584dbd30625c0cf17436b77ff7d777955d"
other = "✅Editor removido '{{.Editor}}'"

[CmdEnableDescription]
hash = "sha1-80a1a19186d5f5ed7cce247774ece534fd1836d7"
other = "Habilita um comando para todos os usuarios no canal"

[CmdGameDescription]
hash = "sha1-238c8a097baa3580e3503bb5b89695ffaa0c6dfe"
other = "Duelo com emotes do fatasswizardcat"

[CmdHelpDescription]
hash = "sha1-3082ecfca0d1b2b40b0ce042ccef7813e5a72565"
other = "Obtenha a lista completa de comandos, ou ajuda com um comando especifico"

[CmdJoinDescription]
hash = "sha1-75646e23ce95ba46fe9ca0869728e3f7eb5461af"
other = "Entra com o bot no canal do autor da mensagem ou no canal especificado"

[CmdJoinResult]
hash = "sha1-fecf28506ece7d1d81a277b263e36fa54ae69de4"
many = "✅Canais ingressados {{.Channels}}"
one = "✅Canal ingressado {{.Channels}}"
other = "✅Canais ingressados {{.Channels}}"

[CmdLanguageDescription]
hash = "sha1-9ff103e0943358adf677df972b0193aeafec91ff"
other = "Altera a linguagem das respostas do bot para o canal do autor ou para um canal especificado"

[CmdLocationDescription]
hash = "sha1-2f110197f8463949b2f1b71a8a456fd10f558782"
other = "Alterar ou obter a localização de um usuário. Usado em comandos relacionados a clima e tempo."

[CmdLocationDisallowedSetLang]
hash = "sha1-bd731bde91eef9fe94827d17508d0dbab852b42d"
other = "Não autorizado a mudar a linguagem para '{{.User}}'."

[CmdLocationFailedToSet]
hash = "sha1-cfc5eeec9f0c50ac8c98d2bb854e670b16cb4d47"
other = "Falha ao alterar a localização de {{.User}} para '{{.Location}}'."

[CmdLocationGet]
hash = "sha1-761ee2fd4459633892ec713f38a7e24500cbaa2e"
other = "A localização do usuário {{.User}} é '{{.Location}}'"

[CmdLocationNotFound]
hash = "sha1-bd1f07710b84601d4a5b2ba0e58511a8ab6f7c8b"
other = "Localização '{{.Location}}' não encontrada."

[CmdLocationNotSet]
hash = "sha1-8ea06c66315cd61fe899162eac75f549d3356a58"
other = "Localização não definida para o usuário '{{.User}}'."

[CmdLocationSuccess]
hash = "sha1-65ce633a6f72c757cfed6ae29c2bfc707f4110e7"
other = "✅Localização de '{{.User}}' alterada para '{{.Location}}'."

[CmdLocationTargetNotFound]
hash = "sha1-86810ea2aab7ae5480895c079f7e36244a734fd5"
other = "Usuário '{{.User}}' não encontrado."

[CmdOptedIn]
hash = "sha1-70f16bd992166ad81cb70fc1cb496d5969a0dfd0"
other = "✅ Resposta a comando habilitada"

[CmdOptionDescription]
hash = "sha1-5a758a9467baee017c93d611836678417f5929f3"
other = "Habilitar a resposta para você a um ou mais comandos"

[CmdOptoutDescription]
hash = "sha1-75ca2c4656c63b39704adca642b78eefeb9d1c20"
other = "Desabilitar a resposta do bot para você a um ou mais comandos"

[CmdPartDescription]
hash = "sha1-49580e8e08cb2fe25547d02bccf23407623e1051"
other = "Deixar o canal do autor ou do canal especificado"

[CmdPartNotJoined]
hash = "sha1-0649c6fe85f9d3a0e909dd1dea0aef1b3fd9227c"
other = "❌Os seguintes canais não foram ingressados: {{.Channels}}"

[CmdPartResult]
hash = "sha1-6be6bbbdfdc3f73d5727cf72775c90a035af39d0"
other = "✅Canais deixados com sucesso: {{.Channels}}"

[CmdPingDescription]
hash = "sha1-8b05ef79c4518c1d8e5f51fce751a94e8ddffec9"
other = "Responde com pong e a latencia para a twitch em milisegundos"

[CmdPingLatency]
hash = "sha1-93c3d7b64824683398d27c9b2921ec6637726794"
other = "Latência: %dms"

[CmdPingMemory]
hash = "sha1-6a3e8d9de5351d63bbb78a3b5989da7749f9b2a4"
other = "Memória: %d MiB"

[CmdPingUptime]
hash = "sha1-0c983159b1173fc1ed8e3a6be1e20c89aa81d8e3"
other = "Tempo de atividade: %s"

[CmdRemoveDescription]
hash = "sha1-d7859c44b54a742196bd31632fd7469e83939199"
other = "Remover o emote 7TV do canal"

[CmdSetLevelDescription]
hash = "sha1-6816b2c469606f4faae17fb7cad8d8b8b83c8539"
other = "Alterar o nivel de permissão do usuario"

[CmdTimeFailedToLoadLocation]
hash = "sha1-42c83e904c42bb7cccc7cc3f8c9dd7b7e75989fc"
other = "Falha ao carregar o fuso horário '{{.Timezone}}' do usuário {{.User}}"

[CmdTimeNotSet]
hash = "sha1-28dbf23b58482085734113a5f8fe430ff4446349"
other = "Localização não definida para {{.User}}."

[CmdTimeResult]
hash = "sha1-7fb3a4b3ba1c87538910d69ef52d430ea0910825"
other = "O tempo para o usuário {{.User}} é '{{.Time}}'"

[CmdTimeTargetNotFound]
hash = "sha1-e9885e594b5237afd95a5806a3a67d6ccdfb4fa1"
other = "Usuário {{.User}} não encontrado."

[CmdWeatherApparentTemp]
hash = "sha1-48a69937749c5977674c930c43b61cf9422f244c"
other = " {{.CurrentTemp}}{{.CurrentTempUnits}}, sensação térmica de {{.Temp}}{{.Unit}}. "

[CmdWeatherCloudCover]
hash = "sha1-ca590036eaf3bd54d8400343c00ffdec996cdf4d"
other = "Cobertura de nuvens: {{.Cover}}{{.Unit}}. "

[CmdWeatherDescription]
hash = "sha1-200e091a3d4d799113b60d74603d78d8b7cb7aa2"
other = "Obtenha o clima atual para um usuário com base na localização definida."

[CmdWeatherFailedToLoadLocation]
hash = "sha1-79d4bc7d3e9414e0b537b2d6aaae0f2a536eb310"
other = "Falha ao carregar o clima para '{{.Name}}'"

[CmdWeatherNoRain]
hash = "sha1-59331462e10c31973249be0ce127b26b18dbe424"
other = "Sem chuva. "

[CmdWeatherRain]
hash = "sha1-9d46c5f86fd87224f6542dc7bc3e5f3548c4169e"
other = "Chuva: {{.Rain}}{{.Unit}}. "

[CmdWeatherSnowfall]
hash = "sha1-c2dc734174dff16322126b6c091a249d8a5b7243"
other = "Neve: {{.Snowfall}}{{.Unit}}. "

[CmdWeatherWindspeed]
hash = "sha1-312a3ed17407ff728e2344a4baad0338adb9e1a8"
other = "Velocidade do vento: {{.Speed}}{{.Unit}}. "

[CmdYoinkDescription]
hash = "sha1-58832ea04838e11effe73cfe0d138f45a58b1797"
other = "Adicionar o emote 7TV de um canal para outro"

[CmdtimeDescription]
hash = "sha1-c315e1844ed21bf78a2699866f7061e68f471ae4"
other = "Obtenha o tempo do usuário com base na localização definida."

[CommandCannotBeDisabled]
hash = "sha1-351a7779ee898f5f87629e70e3cd9f5a99f47597"
other = "❌Comando '{{.Command}}' não pode ser desabilitado"

[DisabledCommands]
hash = "sha1-dafe56f34bc94038b86c678376782fdb2b9c05d6"
other = "✅Comando desabilitado '{{.Command}}'"

[DuelExists]
hash = "sha1-3306c7ee611a20d72963fbed90e3352f4cfe9f5b"
other = "Um dos jogadores ja possui um duelo ativo"

[DuelNoTarget]
hash = "sha1-8d21bf153c7201f28dc13f4b8c3f1ca6bd284df6"
other = "Favor selecionar um alvo"

[DuelNotExists]
hash = "sha1-0850026cfc7e73a8e81ed030b0d4f2b276b6a9b1"
other = "Nenhum duelo ativo encontrado para o jogador"

[DuelStart]
hash = "sha1-216da1db183add34672d06fb841c42feaa75c41f"
other = "duelo iniciado! Seu turno {{.Player}}. Opções são: fireball, water"

[DuelWon]
hash = "sha1-deb582d1f8e3f89bc115a3a0a6cd85a62f874fe7"
other = "{{.Winner}} ganhou! 👏"

[EmoteAlreadyInChannel]
hash = "sha1-7785852466c466fee9013235f2ad6378375e09c9"
other = "❌Emote '{{.Emote}}' já presente em '{{.ToChannel}}'."

[EmotesAlreadyInChannel]
hash = "sha1-7d353e6f7ea9677559edf31f5bf10ae87ae162d3"
many = "❌Emotes '{{.Emotes}}' já presentes em '{{.ToChannel}}'."
one = "❌Emote '{{.Emotes}}' já presente em '{{.ToChannel}}'."
other = "❌Emotes '{{.Emotes}}' já presentes em '{{.ToChannel}}'."

[EnabledCommands]
hash = "sha1-a25f11fed019b9a47a15abb22cd8e9318a78d098"
other = "✅Comando '{{.Command}}' habilitado"

[FailedFetchSevenTVChannel]
hash = "sha1-51f68f0a308100ebfaf7c0207c22e1f64acc061f"
other = "Falha ao obter canal do 7TV para '{{.Channel}}'"

[FailedFetchSevenTVChannel2]
hash = "sha1-51f68f0a308100ebfaf7c0207c22e1f64acc061f"
other = "Falha ao obter o canal 7TV '{{.Channel}}'"

[FailedFindActiveEmoteSet]
hash = "sha1-7642a9f84df52353843b9aa1b2440ef50f22f906"
other = "❌Falha ao obter set ativo de emotes para {{.Channel}}"

[FailedFindEmote]
hash = "sha1-eaaa2fe8269c91578a916866aa850064d36d64c9"
many = "❌Falha ao encontrar emotes '{{.Emotes}}' em '{{.Channel}}'."
one = "❌Falha ao encontrar emotes '{{.Emotes}}' em '{{.Channel}}'."
other = "❌Falha ao encontrar emotes '{{.Emotes}}' em '{{.Channel}}'."

[FailedToFetchChannel]
hash = "sha1-857162b6daacf48d51955e12bd802406e092f931"
other = "❌Falha ao obter canal '{{.Channel}}'"

[Help]
hash = "sha1-7b7e88484c70a67b856b826dbfdf4afcd7364938"
other = "Comandos: http://hashbot.dev ● Para ajuda com um comando especifico: help <comando>"

[MustBeAdmin]
hash = "sha1-a50adcc3e7f5328d97dcff1a6bd90c32226452e3"
other = "❌Você deve ser um admin para utilizar esse comando"

[MustBeModerator]
hash = "sha1-d4c9682ff6f478ccd338d84a906d200348618fe7"
other = "❌Você deve ser um moderador para usar esse comando"

[NotAnEditor]
hash = "sha1-98d6fab7fd814ecf928bad589ba24f2b5c1117b6"
other = "❌Usuário'{{.User}}' não adicionou o bot como editor."

[NotEditor]
hash = "sha1-4715edccc4607599079258d6f3fe3367112c4747"
other = "❌Você deve ser um editor para usar esse comando"

[OptedOut]
hash = "sha1-9b6c76817f0c83092ead108739c7db7d901cdab8"
other = "✅ Desabilitado"

[SetBarrierEffect]
hash = "sha1-63e223c9be4e2b66cae212b5ea27fc8d2c282d32"
other = "{{.Source}} aplicou uma barreira => {{.Action}} {{.Barrier}}🛡️"

[SetDamageEffect]
hash = "sha1-d05ca37af80542767aac49fd0e497d9ad95766ca"
other = "{{.Source}} atacou {{.Target}} => {{.Action}} {{.Health}}❤️ - {{.Damage}}❤️ = {{.HpLeft}}❤️"

[SetHPEffect]
hash = "sha1-46714d720e42ffaffd99a0f7e40829c8261f2cca"
other = "{{.Source}} se curou => {{.Action}} {{.HP}}🧪"

[SetUserLanguageFail]
hash = "sha1-9e27fe58a9469d72ddb1eb32fe866d43a055a21b"
other = "❌Falha ao alterar a linguagem do usuario"

[SetUserLanguageResult]
hash = "sha1-32f75710d477c2394b55421bdb661e2edb5752f5"
other = "✅Linguagem de {{.Username}} alterada para {{.Language}}"

[UnknownCommand]
hash = "sha1-85fb54b67a702394582f5eb86244d3ea6a4daada"
other = "❌Comando desconhecido '{{.Command}}'."

[UpdatedPermissions]
hash = "sha1-3560aeac51233270b83aeca0375ce9ff18d50dde"
other = "✅ Atualizadas as permissões de {{.User}} para {{.Permission}}!"

[Usage]
hash = "sha1-2e1344a4d86aeb9f15e1572706cba842ac8052ab"
other = "❌Uso: {{.Usage}}"

[UserNotFound]
hash = "sha1-2f6790031f3fddca6adc2194cf1762fea194f4cc"
other = "Usuário '{{.User}}' não encontrado"

[WrongTurn]
hash = "sha1-ce2d5607858624457a89f9c242c00fc4e5ff1214"
other = "a próxima jogada é de {{.Target}}, não sua!"

[YoinkFromChannelToChannel]
hash = "sha1-86ccedc2488d513a36905c33a730deffb8899e98"
other = "❌Não é possível adicionar de '{{.From}}' para '{{.To}}', eles são iguais."
