FROM golang:1.24

WORKDIR /usr/src

COPY . .
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go mod download
RUN go env -w GOFLAGS=-buildvcs=false
RUN go build -gcflags="-N -l" -o /usr/src/app main.go

EXPOSE 8080
CMD ["dlv", "debug", "--headless=true", "--listen=0.0.0.0:2345", "--api-version=2", "--accept-multiclient", "--", "/usr/src/app", "-cfg", "config.json", "-debug"]

