services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src
      - $HOME/.hashbot_db:/database
    depends_on:
      - cloudflare-tunnel

  node-server:
    image: node:22
    depends_on:
      - cloudflare-tunnel
    working_dir: /usr/src/app
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - "80:3000"
    command: >
      sh -c "npm install || exit 1 && npm run build || exit 1 && node build"
