services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    userns: keep-id
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src:rw,Z
    networks:
      - cloudflare_tunnel_network

  node-server:
    build:
      context: .
      dockerfile: Dockerfile.Node
    userns: keep-id
    working_dir: /usr/src
    restart: always
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run build && node build"
    networks:
      - cloudflare_tunnel_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel run --token $TUNNEL_TOKEN
    networks:
      - cloudflare_tunnel_network

networks:
  cloudflare_tunnel_network:
    name: cloudflare_tunnel_network
