name: podswap

on:
  push:
    branches:
      - 'main'

jobs:
  podswap:
    uses: douglascdev/podswap/.github/workflows/action.yml@main
    secrets:
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    with:
      pre-build-cmd: 'git pull && podman image prune'
      build-cmd: 'podman compose build'
      deploy-cmd: 'podman compose up -d --force-recreate'
